version: "3.9"

services:
    app:
        container_name: app
        image: app
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:8080"